default: &default
  adapter:  postgresql
  encoding: unicode
  pool:     5
  username: pooja
  password: pooja
  database: <%= Rails.application.credentials.config[:DB_DATABASE] %>

development:
  <<: *default
  database: edyou_development

test:
  <<: *default
  database: edyou_test

staging:
  <<: *default
  database: edyou_staging
