default: &default
  adapter:  postgresql
  encoding: unicode
  pool:     5
  username: pooja
  password: pooja

development:
  <<: *default
  database: edyou_development

test:
  <<: *default
  database: edyou_test

staging:
  <<: *default
  database: edyou_staging
