# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# # # # # # # # # # # # # # # # # # # # # # # # # # #
#                Feeling List                       #
# # # # # # # # # # # # # # # # # # # # # # # # # # #
Feeling.find_or_create_by(name: 'Happy')
Feeling.find_or_create_by(name: 'Blessed')
Feeling.find_or_create_by(name: 'Loved')
Feeling.find_or_create_by(name: 'Sad')
Feeling.find_or_create_by(name: 'Lovely')
Feeling.find_or_create_by(name: 'Thankful')
Feeling.find_or_create_by(name: 'Excited')
Feeling.find_or_create_by(name: 'In Love')
Feeling.find_or_create_by(name: 'Crazy')
Feeling.find_or_create_by(name: 'Grateful')
Feeling.find_or_create_by(name: 'Blissful')
Feeling.find_or_create_by(name: 'Fatastic')
Feeling.find_or_create_by(name: 'Silly')
Feeling.find_or_create_by(name: 'Festive')
Feeling.find_or_create_by(name: 'Wonderful')
Feeling.find_or_create_by(name: 'Cool')
Feeling.find_or_create_by(name: 'Amused')
Feeling.find_or_create_by(name: 'Relaxed')
Feeling.find_or_create_by(name: 'Positive')
Feeling.find_or_create_by(name: 'Chill')
Feeling.find_or_create_by(name: 'Hopeful')
Feeling.find_or_create_by(name: 'Joyful')
Feeling.find_or_create_by(name: 'Tired')
Feeling.find_or_create_by(name: 'Motivated')
Feeling.find_or_create_by(name: 'Proud')
Feeling.find_or_create_by(name: 'Alone')
Feeling.find_or_create_by(name: 'Thoughtful')
Feeling.find_or_create_by(name: 'OK')
Feeling.find_or_create_by(name: 'Nostalgic')
Feeling.find_or_create_by(name: 'Angry')
Feeling.find_or_create_by(name: 'Sick')
Feeling.find_or_create_by(name: 'Delighted')
Feeling.find_or_create_by(name: 'Drained')
Feeling.find_or_create_by(name: 'Emotional')
Feeling.find_or_create_by(name: 'Confident')
Feeling.find_or_create_by(name: 'Awesome')
Feeling.find_or_create_by(name: 'Fresh')
Feeling.find_or_create_by(name: 'Determined')
Feeling.find_or_create_by(name: 'Exhausted')
Feeling.find_or_create_by(name: 'Annoyed')
Feeling.find_or_create_by(name: 'Glad')
Feeling.find_or_create_by(name: 'Lucky')
Feeling.find_or_create_by(name: 'Heartbroken')
Feeling.find_or_create_by(name: 'Bored')
Feeling.find_or_create_by(name: 'Sleepy')
Feeling.find_or_create_by(name: 'Energised')
Feeling.find_or_create_by(name: 'Hungry')
Feeling.find_or_create_by(name: 'Professional')
Feeling.find_or_create_by(name: 'Pained')
Feeling.find_or_create_by(name: 'Peaceful')
Feeling.find_or_create_by(name: 'Disappointed')
Feeling.find_or_create_by(name: 'Optimistic')
Feeling.find_or_create_by(name: 'Cold')
Feeling.find_or_create_by(name: 'Cute')
Feeling.find_or_create_by(name: 'Fabulous')
Feeling.find_or_create_by(name: 'Great')
Feeling.find_or_create_by(name: 'Happy')
Feeling.find_or_create_by(name: 'Sorry')
Feeling.find_or_create_by(name: 'Super')
Feeling.find_or_create_by(name: 'Worried')
Feeling.find_or_create_by(name: 'Funny')
Feeling.find_or_create_by(name: 'Bad')
Feeling.find_or_create_by(name: 'Down')
Feeling.find_or_create_by(name: 'Inspired')
Feeling.find_or_create_by(name: 'Satisfied')
Feeling.find_or_create_by(name: 'Pumped')
Feeling.find_or_create_by(name: 'Calm')
Feeling.find_or_create_by(name: 'Confused')
Feeling.find_or_create_by(name: 'Goofy')
Feeling.find_or_create_by(name: 'Missing')
Feeling.find_or_create_by(name: 'Good')
Feeling.find_or_create_by(name: 'Sarcastic')
Feeling.find_or_create_by(name: 'Lonely')
Feeling.find_or_create_by(name: 'Strong')
Feeling.find_or_create_by(name: 'Concerned')
Feeling.find_or_create_by(name: 'Special')
Feeling.find_or_create_by(name: 'Depressed')
Feeling.find_or_create_by(name: 'Jolly')
Feeling.find_or_create_by(name: 'Curious')
Feeling.find_or_create_by(name: 'Low')
Feeling.find_or_create_by(name: 'Welcome')
Feeling.find_or_create_by(name: 'Broken')
Feeling.find_or_create_by(name: 'Beautiful')
Feeling.find_or_create_by(name: 'Amazing')
Feeling.find_or_create_by(name: 'Irritated')
Feeling.find_or_create_by(name: 'Stressed')
Feeling.find_or_create_by(name: 'Incomplete')
Feeling.find_or_create_by(name: 'Hyper')
Feeling.find_or_create_by(name: 'Mischievous')
Feeling.find_or_create_by(name: 'Amazed')
Feeling.find_or_create_by(name: 'Annoyed')
Feeling.find_or_create_by(name: 'Fed Up')
Feeling.find_or_create_by(name: 'Puzzled')
Feeling.find_or_create_by(name: 'Furious')
Feeling.find_or_create_by(name: 'Annoyed')
Feeling.find_or_create_by(name: 'Refreshed')
Feeling.find_or_create_by(name: 'Accomplished')
Feeling.find_or_create_by(name: 'Surprised')
Feeling.find_or_create_by(name: 'Perplexed')
Feeling.find_or_create_by(name: 'Frustrated')
Feeling.find_or_create_by(name: 'Meh')
Feeling.find_or_create_by(name: 'Pretty')
Feeling.find_or_create_by(name: 'Better')
Feeling.find_or_create_by(name: 'Guilty')
Feeling.find_or_create_by(name: 'Safe')
Feeling.find_or_create_by(name: 'Free')
Feeling.find_or_create_by(name: 'Lost')
Feeling.find_or_create_by(name: 'Old')
Feeling.find_or_create_by(name: 'Lazy')
Feeling.find_or_create_by(name: 'Worse')
Feeling.find_or_create_by(name: 'Horrible')
Feeling.find_or_create_by(name: 'Comfortable')
Feeling.find_or_create_by(name: 'Stupid')
Feeling.find_or_create_by(name: 'Ashamed')
Feeling.find_or_create_by(name: 'Terrible')
Feeling.find_or_create_by(name: 'Asleep')
Feeling.find_or_create_by(name: 'Well')
Feeling.find_or_create_by(name: 'Alive')
Feeling.find_or_create_by(name: 'Shy')
Feeling.find_or_create_by(name: 'Rough')
Feeling.find_or_create_by(name: 'Weird')
Feeling.find_or_create_by(name: 'Human')
Feeling.find_or_create_by(name: 'Hurt')
Feeling.find_or_create_by(name: 'Awful')

# # # # # # # # # # # # # # # # # # # # # # # # # # #
#               Activity List                       #
# # # # # # # # # # # # # # # # # # # # # # # # # # #
parent_activity = Activity.find_or_create_by(name: 'Celebrating')
Activity.find_or_create_by(name: 'friendship', parent_id: parent_activity.id)
Activity.find_or_create_by(name: 'a birthday', parent_id: parent_activity.id)
Activity.find_or_create_by(name: 'your special day', parent_id: parent_activity.id)
Activity.find_or_create_by(name: 'birthdays', parent_id: parent_activity.id)
Activity.find_or_create_by(name: 'Christmas', parent_id: parent_activity.id)
Activity.find_or_create_by(name: "New Year's Eve", parent_id: parent_activity.id)
Activity.find_or_create_by(name: 'this special day', parent_id: parent_activity.id)
Activity.find_or_create_by(name: "my brother's birthday", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "the Queen's birthday", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "my sister's birthday", parent_id: parent_activity.id)
Activity.find_or_create_by(name: 'my birthday', parent_id: parent_activity.id)
Activity.find_or_create_by(name: 'success', parent_id: parent_activity.id)
Activity.find_or_create_by(name: 'the holidays', parent_id: parent_activity.id)
Activity.find_or_create_by(name: 'another year of life', parent_id: parent_activity.id)
Activity.find_or_create_by(name: 'our wedding anniversary', parent_id: parent_activity.id)
Activity.find_or_create_by(name: 'love', parent_id: parent_activity.id)
Activity.find_or_create_by(name: "my mum's birthday", parent_id: parent_activity.id)
Activity.find_or_create_by(name: 'life', parent_id: parent_activity.id)
Activity.find_or_create_by(name: 'another year', parent_id: parent_activity.id)
Activity.find_or_create_by(name: 'Thanksgiving', parent_id: parent_activity.id)
Activity.find_or_create_by(name: 'victory', parent_id: parent_activity.id)
Activity.find_or_create_by(name: "my dad's birthday", parent_id: parent_activity.id)
Activity.find_or_create_by(name: 'this day', parent_id: parent_activity.id)
Activity.find_or_create_by(name: 'holidays', parent_id: parent_activity.id)
Activity.find_or_create_by(name: 'Makar Sankranti', parent_id: parent_activity.id)
Activity.find_or_create_by(name: 'our anniversary', parent_id: parent_activity.id)
Activity.find_or_create_by(name: 'your big day', parent_id: parent_activity.id)
Activity.find_or_create_by(name: 'our special day', parent_id: parent_activity.id)
Activity.find_or_create_by(name: 'another birthday', parent_id: parent_activity.id)
Activity.find_or_create_by(name: 'graduation', parent_id: parent_activity.id)
Activity.find_or_create_by(name: 'engagement', parent_id: parent_activity.id)
Activity.find_or_create_by(name: 'Pongal', parent_id: parent_activity.id)
Activity.find_or_create_by(name: 'your day', parent_id: parent_activity.id)
Activity.find_or_create_by(name: 'their birthdays', parent_id: parent_activity.id)
Activity.find_or_create_by(name: 'the season', parent_id: parent_activity.id)
Activity.find_or_create_by(name: 'my special day', parent_id: parent_activity.id)
Activity.find_or_create_by(name: 'your life', parent_id: parent_activity.id)
Activity.find_or_create_by(name: 'every day', parent_id: parent_activity.id)
Activity.find_or_create_by(name: 'baby shower', parent_id: parent_activity.id)
Activity.find_or_create_by(name: 'Friday', parent_id: parent_activity.id)
Activity.find_or_create_by(name: 'something', parent_id: parent_activity.id)
Activity.find_or_create_by(name: 'community', parent_id: parent_activity.id)
Activity.find_or_create_by(name: 'this weekend', parent_id: parent_activity.id)
Activity.find_or_create_by(name: 'our wedding', parent_id: parent_activity.id)
Activity.find_or_create_by(name: 'recovery', parent_id: parent_activity.id)
Activity.find_or_create_by(name: 'winter', parent_id: parent_activity.id)
Activity.find_or_create_by(name: 'hump day', parent_id: parent_activity.id)
Activity.find_or_create_by(name: 'my new job', parent_id: parent_activity.id)
Activity.find_or_create_by(name: 'our birthdays', parent_id: parent_activity.id)
Activity.find_or_create_by(name: "Valentine's Day", parent_id: parent_activity.id)
Activity.find_or_create_by(name: 'Independence Day', parent_id: parent_activity.id)
Activity.find_or_create_by(name: 'the first day of winter', parent_id: parent_activity.id)
Activity.find_or_create_by(name: 'Boxing Day', parent_id: parent_activity.id)
Activity.find_or_create_by(name: "Children's Day", parent_id: parent_activity.id)
Activity.find_or_create_by(name: 'Thanksgiving Day', parent_id: parent_activity.id)
Activity.find_or_create_by(name: 'Saturday', parent_id: parent_activity.id)
Activity.find_or_create_by(name: "Friends' Day", parent_id: parent_activity.id)
Activity.find_or_create_by(name: 'peace', parent_id: parent_activity.id)
Activity.find_or_create_by(name: 'Fourth of July', parent_id: parent_activity.id)
Activity.find_or_create_by(name: "Father's Day", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "Lovers' Day", parent_id: parent_activity.id)
Activity.find_or_create_by(name: 'spring', parent_id: parent_activity.id)
Activity.find_or_create_by(name: 'summer', parent_id: parent_activity.id)
Activity.find_or_create_by(name: 'Ramadan', parent_id: parent_activity.id)
Activity.find_or_create_by(name: 'Eid', parent_id: parent_activity.id)
Activity.find_or_create_by(name: 'Easter Sunday', parent_id: parent_activity.id)
Activity.find_or_create_by(name: 'Halloween', parent_id: parent_activity.id)
Activity.find_or_create_by(name: 'Holi', parent_id: parent_activity.id)
Activity.find_or_create_by(name: 'Easter', parent_id: parent_activity.id)
Activity.find_or_create_by(name: "Mother's Day", parent_id: parent_activity.id)
parent_activity = Activity.find_or_create_by(name: 'Watching')
parent_activity = Activity.find_or_create_by(name: 'Eating')
Activity.find_or_create_by(name: "lunch", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "dinner", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "Starbucks", parent_id: parent_activity.id)
parent_activity = Activity.find_or_create_by(name: 'Drinking')
parent_activity = Activity.find_or_create_by(name: 'Attending')
Activity.find_or_create_by(name: "church", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "a wedding", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "an event", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "a birthday party", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "a Christmas party", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "work", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "a live concert", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "a meeting", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "Sunday mass", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "a marriage ceremony", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "a training", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "mass", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "a basketball game", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "a seminar", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "a wedding reception", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "a party", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "a conference", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "school/college/university", parent_id: parent_activity.id)
parent_activity = Activity.find_or_create_by(name: 'Traveling to')
parent_activity = Activity.find_or_create_by(name: 'Listening to')
parent_activity = Activity.find_or_create_by(name: 'Looking for')
Activity.find_or_create_by(name: "advice", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "help", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "a miracle", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "answers", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "ideas", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "prayers", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "perfection", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "birthday present recommendations", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "Nessie", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "balance", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "travel recommendations", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "a trip", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "an angel", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "cuddles", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "donations", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "dinosaurs", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "easy money", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "ufos", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "Bigfoot", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "a boyfriend", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "a mobile phone", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "great music", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "shoes", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "film recommendations", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "a full-time employee", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "a housemate", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "a Christmas tree", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "a doctor", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "restaurant recommendations", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "a car", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "photographer recommendations", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "a dog", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "dentist recommendations", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "a beer", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "food", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "a babysitter", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "job recommendations", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "a kind soul", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "doctor recommendations", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "a tattoo artist", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "food recommendations", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "ice cream", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "the holy grail", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "a workout", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "car recommendations", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "alcohol", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "great food", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "salon recommendations", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "a book", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "a brain", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "Prince Charming", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "music", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "something to watch", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "a date night", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "a cat", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "a magician", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "flowers", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "love in all the wrong places", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "a part-time job", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "a hair stylist", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "a home", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "salvation", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "fish", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "motivation", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "more friends", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "a massage", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "chocolate", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "a partner in crime", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "a partner", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "medicine", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "peace", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "a job", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "inspiration", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "hope", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "volunteers", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "sheep", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "book recommendations", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "employees", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "fun people", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "love", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "intelligent life", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "home recommendations", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "the sun", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "a photographer", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "four-leaf clovers", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "a motorcycle", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "a new car", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "a new house", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "investors", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "a cake", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "hotel recommendations", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "clothes", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "a nail salon", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "pumpkins", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "things to do", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "a great workout", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "a super hero", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "a girlfriend", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "an adventure", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "sunshine", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "friends", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "happiness", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "something to do", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "a best friend", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "the meaning of life", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "photos", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "fun", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "money", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "God", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "a full-time job", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "coffee", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "recommendations", parent_id: parent_activity.id)
parent_activity = Activity.find_or_create_by(name: 'Thinking about')
Activity.find_or_create_by(name: "old memories", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "the meaning of life", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "making a change", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "my future", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "someone special", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "a lot of things", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "doing something different", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "all the good times", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "life", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "friends and family", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "better days", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "a holiday", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "doing something crazy", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "my mum", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "my son", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "my daughter", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "all my friends", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "my birthday", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "tomorrow", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "my girlfriend", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "going back to school", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "buying a car", parent_id: parent_activity.id)
parent_activity = Activity.find_or_create_by(name: 'Reading')
parent_activity = Activity.find_or_create_by(name: 'Playing')
Activity.find_or_create_by(name: "soccer", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "basketball", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "cricket", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "Baseball", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "Xbox", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "Video Games", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "Chess", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "playing cards", parent_id: parent_activity.id)
Activity.find_or_create_by(name: "board games", parent_id: parent_activity.id)
parent_activity = Activity.find_or_create_by(name: 'Supporting')

# # # # # # # # # # # # # # # # # # # # # # # # # # #
#               Permission List                     #
# # # # # # # # # # # # # # # # # # # # # # # # # # #
Permission.find_or_create_by(action_name: "Public", action_description: "Anyone on or off EdYou", action: "public",  action_object: 'Post')
Permission.find_or_create_by(action_name: "Friends", action_description: "Your friends on EdYou", action: "friends", action_object: 'Post')
Permission.find_or_create_by(action_name: "Friends, except...", action_description: "Don't show to some friends", action: "except_friends", action_object: 'Post')
Permission.find_or_create_by(action_name: "Specific friends...", action_description: "Only show to some friends", action: "specific_friends", action_object: 'Post')
Permission.find_or_create_by(action_name: "Only me", action_description: "Only me", action: "private",  action_object: 'Post')
Permission.find_or_create_by(action_name: "Close friends", action_description: "Your custom list", action: "close_friends", action_object: 'Post')
Permission.find_or_create_by(action_name: "Public", action_description: "Anyone on or off EdYou", action: "public",  action_object: 'Album')
Permission.find_or_create_by(action_name: "Friends", action_description: "Your friends on EdYou", action: "friends", action_object: 'Album')
Permission.find_or_create_by(action_name: "Friends, except...", action_description: "Don't show to some friends", action: "except_friends", action_object: 'Album')
Permission.find_or_create_by(action_name: "Specific friends...", action_description: "Only show to some friends", action: "specific_friends", action_object: 'Album')
Permission.find_or_create_by(action_name: "Only me", action_description: "Only me", action: "private",  action_object: 'Album')
Permission.find_or_create_by(action_name: "Close friends", action_description: "Your custom list", action: "close_friends", action_object: 'Album')
Permission.find_or_create_by(action_name: "Friends of contributors", action_description: "Contributors and their friends", action: "contributors_friends",  action_object: 'Album')
Permission.find_or_create_by(action_name: "Contributors Only", action_description: "Only contributors added to this album", action: "contributors", action_object: 'Album')
