# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# # # # # # # # # # # # # # # # # # # # # # # # # # #
#                Feeling List                       #
# # # # # # # # # # # # # # # # # # # # # # # # # # #
Feeling.find_or_create_by(name: 'Happy', emoji_symbol: '0x1F642')
Feeling.find_or_create_by(name: 'Blessed', emoji_symbol: '0x1F607')
Feeling.find_or_create_by(name: 'Loved', emoji_symbol: '0x1F970')
Feeling.find_or_create_by(name: 'Sad', emoji_symbol: '0x1F641')
Feeling.find_or_create_by(name: 'Lovely', emoji_symbol: '0x1F970')
Feeling.find_or_create_by(name: 'Thankful', emoji_symbol: '0x1F601')
Feeling.find_or_create_by(name: 'Excited' , emoji_symbol: '0x1F604')
Feeling.find_or_create_by(name: 'In Love', emoji_symbol: '0x1F970')
Feeling.find_or_create_by(name: 'Crazy', emoji_symbol: '0x1F61C')
Feeling.find_or_create_by(name: 'Grateful', emoji_symbol: '0x1F601')
Feeling.find_or_create_by(name: 'Blissful', emoji_symbol: '0x1F60A')
Feeling.find_or_create_by(name: 'Fatastic', emoji_symbol: '0x1F929')
Feeling.find_or_create_by(name: 'Silly', emoji_symbol: '0x1F61B')
Feeling.find_or_create_by(name: 'Festive', emoji_symbol: '0x1F973')
Feeling.find_or_create_by(name: 'Wonderful', emoji_symbol: '0x1F642')
Feeling.find_or_create_by(name: 'Cool', emoji_symbol: '0x1F60E')
Feeling.find_or_create_by(name: 'Amused', emoji_symbol: '0x1F642')
Feeling.find_or_create_by(name: 'Relaxed', emoji_symbol: '0x1F60C')
Feeling.find_or_create_by(name: 'Positive', emoji_symbol: '0x1F60C')
Feeling.find_or_create_by(name: 'Chill', emoji_symbol: '0x1F60C')
Feeling.find_or_create_by(name: 'Hopeful', emoji_symbol: '0x1F337')
Feeling.find_or_create_by(name: 'Joyful', emoji_symbol: '0x1263A')
Feeling.find_or_create_by(name: 'Tired', emoji_symbol: '0x1F634')
Feeling.find_or_create_by(name: 'Motivated', emoji_symbol: '0x1F603')
Feeling.find_or_create_by(name: 'Proud', emoji_symbol: '0x1F603')
Feeling.find_or_create_by(name: 'Alone', emoji_symbol: '0x1F614')
Feeling.find_or_create_by(name: 'Thoughtful', emoji_symbol: '0x1F928')
Feeling.find_or_create_by(name: 'OK', emoji_symbol: '0x1F929')
Feeling.find_or_create_by(name: 'Nostalgic', emoji_symbol: '0x1F917')
Feeling.find_or_create_by(name: 'Angry', emoji_symbol: '0x1F620')
Feeling.find_or_create_by(name: 'Sick', emoji_symbol: '0x1F912')
Feeling.find_or_create_by(name: 'Delighted', emoji_symbol: '0x1F973')
Feeling.find_or_create_by(name: 'Drained', emoji_symbol: '0x1F62B')
Feeling.find_or_create_by(name: 'Emotional', emoji_symbol: '0x1F61F')
Feeling.find_or_create_by(name: 'Confident', emoji_symbol: '0x1F603')
Feeling.find_or_create_by(name: 'Awesome', emoji_symbol: '0x1F601')
Feeling.find_or_create_by(name: 'Fresh', emoji_symbol: '0x1F603')
Feeling.find_or_create_by(name: 'Determined', emoji_symbol: '0x1F609')
Feeling.find_or_create_by(name: 'Exhausted', emoji_symbol: '0x1F62A')
Feeling.find_or_create_by(name: 'Annoyed', emoji_symbol: '0x1F620')
Feeling.find_or_create_by(name: 'Glad', emoji_symbol: '0x1F642')
Feeling.find_or_create_by(name: 'Lucky', emoji_symbol: '0x1F60D')
Feeling.find_or_create_by(name: 'Heartbroken', emoji_symbol: '0x12639')
Feeling.find_or_create_by(name: 'Bored', emoji_symbol: '0x1F615')
Feeling.find_or_create_by(name: 'Sleepy', emoji_symbol: '0x1F634')
Feeling.find_or_create_by(name: 'Energised', emoji_symbol: '0x1F973')
Feeling.find_or_create_by(name: 'Hungry', emoji_symbol: '0x1F626')
Feeling.find_or_create_by(name: 'Professional', emoji_symbol: '0x1F603')
Feeling.find_or_create_by(name: 'Pained', emoji_symbol: '0x1F61F')
Feeling.find_or_create_by(name: 'Peaceful', emoji_symbol: '0x1F601')
Feeling.find_or_create_by(name: 'Disappointed', emoji_symbol: '0x1F61E')
Feeling.find_or_create_by(name: 'Optimistic', emoji_symbol: '0x1F603')
Feeling.find_or_create_by(name: 'Cold', emoji_symbol: '0x1F976')
Feeling.find_or_create_by(name: 'Cute', emoji_symbol: '0x1F60A')
Feeling.find_or_create_by(name: 'Fabulous', emoji_symbol: '0x1F60E')
Feeling.find_or_create_by(name: 'Great', emoji_symbol: '0x1F603')
Feeling.find_or_create_by(name: 'Happy', emoji_symbol: '0x1F601')
Feeling.find_or_create_by(name: 'Sorry', emoji_symbol: '0x1F625')
Feeling.find_or_create_by(name: 'Super', emoji_symbol: '0x1F60A')
Feeling.find_or_create_by(name: 'Worried', emoji_symbol: '0x1F61F')
Feeling.find_or_create_by(name: 'Funny', emoji_symbol: '0x1F602')
Feeling.find_or_create_by(name: 'Bad', emoji_symbol: '0x1F614')
Feeling.find_or_create_by(name: 'Down', emoji_symbol: '0x1F61E')
Feeling.find_or_create_by(name: 'Inspired', emoji_symbol: '0x1F60A')
Feeling.find_or_create_by(name: 'Satisfied', emoji_symbol: '0x1F642')
Feeling.find_or_create_by(name: 'Pumped', emoji_symbol: '0x1F609')
Feeling.find_or_create_by(name: 'Calm', emoji_symbol: '0x1F601')
Feeling.find_or_create_by(name: 'Confused', emoji_symbol: '0x1F615')
Feeling.find_or_create_by(name: 'Goofy', emoji_symbol: '0x1F92A')
Feeling.find_or_create_by(name: 'Missing', emoji_symbol: '0x1F627')
Feeling.find_or_create_by(name: 'Good', emoji_symbol: '0x1F642')
Feeling.find_or_create_by(name: 'Sarcastic', emoji_symbol: '0x1F605')
Feeling.find_or_create_by(name: 'Lonely', emoji_symbol: '0x1F614')
Feeling.find_or_create_by(name: 'Strong', emoji_symbol: '0x1F60A')
Feeling.find_or_create_by(name: 'Concerned', emoji_symbol: '0x1F630')
Feeling.find_or_create_by(name: 'Special', emoji_symbol: '0x1F60D')
Feeling.find_or_create_by(name: 'Depressed', emoji_symbol: '0x1F61F')
Feeling.find_or_create_by(name: 'Jolly', emoji_symbol: '0x1263A')
Feeling.find_or_create_by(name: 'Curious', emoji_symbol: '0x1F914')
Feeling.find_or_create_by(name: 'Low', emoji_symbol: '0x1F614')
Feeling.find_or_create_by(name: 'Welcome', emoji_symbol: '0x1F642')
Feeling.find_or_create_by(name: 'Broken', emoji_symbol: '0x1F616')
Feeling.find_or_create_by(name: 'Beautiful', emoji_symbol: '0x1F929')
Feeling.find_or_create_by(name: 'Amazing', emoji_symbol: '0x1F60D')
Feeling.find_or_create_by(name: 'Irritated', emoji_symbol: '0x1F60F')
Feeling.find_or_create_by(name: 'Stressed', emoji_symbol: '0x1F612')
Feeling.find_or_create_by(name: 'Incomplete', emoji_symbol: '0x1F613')
Feeling.find_or_create_by(name: 'Hyper', emoji_symbol: '0x1F61C')
Feeling.find_or_create_by(name: 'Mischievous', emoji_symbol: '0x1F60B')
Feeling.find_or_create_by(name: 'Amazed', emoji_symbol: '0x1F973')
Feeling.find_or_create_by(name: 'Fed Up', emoji_symbol: '0x1F624')
Feeling.find_or_create_by(name: 'Puzzled', emoji_symbol: '0x1F615')
Feeling.find_or_create_by(name: 'Furious', emoji_symbol: '0x1F624')
Feeling.find_or_create_by(name: 'Pissed', emoji_symbol: '0x1F621')
Feeling.find_or_create_by(name: 'Refreshed', emoji_symbol: '0x1F642')
Feeling.find_or_create_by(name: 'Accomplished', emoji_symbol: '0x1F60A')
Feeling.find_or_create_by(name: 'Surprised', emoji_symbol: '0x1F633')
Feeling.find_or_create_by(name: 'Perplexed', emoji_symbol: '0x1F614')
Feeling.find_or_create_by(name: 'Frustrated', emoji_symbol: '0x1F629')
Feeling.find_or_create_by(name: 'Meh', emoji_symbol: '0x1F611')
Feeling.find_or_create_by(name: 'Pretty', emoji_symbol: '0x1F929')
Feeling.find_or_create_by(name: 'Better', emoji_symbol: '0x1F604')
Feeling.find_or_create_by(name: 'Guilty', emoji_symbol: '0x1F614')
Feeling.find_or_create_by(name: 'Safe', emoji_symbol: '0x1F60A')
Feeling.find_or_create_by(name: 'Free', emoji_symbol: '0x1F642')
Feeling.find_or_create_by(name: 'Lost', emoji_symbol: '0x1F928')

# # # # # # # # # # # # # # # # # # # # # # # # # # #
#               Activity List                       #
# # # # # # # # # # # # # # # # # # # # # # # # # # #
parent_activity = PostActivity.find_or_create_by(name: 'Celebrating')
PostActivity.find_or_create_by(name: 'friendship', parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: 'a birthday', parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: 'your special day', parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: 'birthdays', parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: 'Christmas', parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "New Year's Eve", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: 'this special day', parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "my brother's birthday", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "the Queen's birthday", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "my sister's birthday", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: 'my birthday', parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: 'success', parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: 'the holidays', parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: 'another year of life', parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: 'our wedding anniversary', parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: 'love', parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "my mum's birthday", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: 'life', parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: 'another year', parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: 'Thanksgiving', parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: 'victory', parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "my dad's birthday", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: 'this day', parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: 'holidays', parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: 'Makar Sankranti', parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: 'our anniversary', parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: 'your big day', parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: 'our special day', parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: 'another birthday', parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: 'graduation', parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: 'engagement', parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: 'Pongal', parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: 'your day', parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: 'their birthdays', parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: 'the season', parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: 'my special day', parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: 'your life', parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: 'every day', parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: 'baby shower', parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: 'Friday', parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: 'something', parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: 'community', parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: 'this weekend', parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: 'our wedding', parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: 'recovery', parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: 'winter', parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: 'hump day', parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: 'my new job', parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: 'our birthdays', parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "Valentine's Day", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: 'Independence Day', parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: 'the first day of winter', parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: 'Boxing Day', parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "Children's Day", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: 'Thanksgiving Day', parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: 'Saturday', parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "Friends' Day", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: 'peace', parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: 'Fourth of July', parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "Father's Day", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "Lovers' Day", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: 'spring', parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: 'summer', parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: 'Ramadan', parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: 'Eid', parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: 'Easter Sunday', parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: 'Halloween', parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: 'Holi', parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: 'Easter', parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "Mother's Day", parent_id: parent_activity.id)
parent_activity = PostActivity.find_or_create_by(name: 'Watching')
parent_activity = PostActivity.find_or_create_by(name: 'Eating')
PostActivity.find_or_create_by(name: "lunch", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "dinner", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "Starbucks", parent_id: parent_activity.id)
parent_activity = PostActivity.find_or_create_by(name: 'Drinking')
parent_activity = PostActivity.find_or_create_by(name: 'Attending')
PostActivity.find_or_create_by(name: "church", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "a wedding", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "an event", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "a birthday party", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "a Christmas party", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "work", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "a live concert", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "a meeting", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "Sunday mass", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "a marriage ceremony", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "a training", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "mass", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "a basketball game", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "a seminar", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "a wedding reception", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "a party", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "a conference", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "school/college/university", parent_id: parent_activity.id)
parent_activity = PostActivity.find_or_create_by(name: 'Traveling to')
parent_activity = PostActivity.find_or_create_by(name: 'Listening to')
parent_activity = PostActivity.find_or_create_by(name: 'Looking for')
PostActivity.find_or_create_by(name: "advice", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "help", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "a miracle", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "answers", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "ideas", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "prayers", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "perfection", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "birthday present recommendations", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "Nessie", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "balance", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "travel recommendations", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "a trip", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "an angel", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "cuddles", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "donations", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "dinosaurs", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "easy money", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "ufos", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "Bigfoot", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "a boyfriend", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "a mobile phone", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "great music", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "shoes", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "film recommendations", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "a full-time employee", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "a housemate", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "a Christmas tree", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "a doctor", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "restaurant recommendations", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "a car", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "photographer recommendations", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "a dog", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "dentist recommendations", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "a beer", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "food", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "a babysitter", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "job recommendations", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "a kind soul", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "doctor recommendations", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "a tattoo artist", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "food recommendations", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "ice cream", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "the holy grail", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "a workout", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "car recommendations", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "alcohol", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "great food", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "salon recommendations", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "a book", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "a brain", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "Prince Charming", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "music", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "something to watch", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "a date night", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "a cat", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "a magician", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "flowers", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "love in all the wrong places", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "a part-time job", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "a hair stylist", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "a home", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "salvation", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "fish", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "motivation", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "more friends", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "a massage", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "chocolate", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "a partner in crime", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "a partner", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "medicine", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "peace", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "a job", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "inspiration", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "hope", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "volunteers", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "sheep", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "book recommendations", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "employees", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "fun people", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "love", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "intelligent life", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "home recommendations", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "the sun", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "a photographer", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "four-leaf clovers", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "a motorcycle", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "a new car", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "a new house", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "investors", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "a cake", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "hotel recommendations", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "clothes", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "a nail salon", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "pumpkins", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "things to do", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "a great workout", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "a super hero", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "a girlfriend", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "an adventure", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "sunshine", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "friends", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "happiness", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "something to do", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "a best friend", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "the meaning of life", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "photos", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "fun", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "money", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "God", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "a full-time job", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "coffee", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "recommendations", parent_id: parent_activity.id)
parent_activity = PostActivity.find_or_create_by(name: 'Thinking about')
PostActivity.find_or_create_by(name: "old memories", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "the meaning of life", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "making a change", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "my future", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "someone special", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "a lot of things", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "doing something different", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "all the good times", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "life", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "friends and family", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "better days", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "a holiday", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "doing something crazy", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "my mum", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "my son", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "my daughter", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "all my friends", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "my birthday", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "tomorrow", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "my girlfriend", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "going back to school", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "buying a car", parent_id: parent_activity.id)
parent_activity = PostActivity.find_or_create_by(name: 'Reading')
parent_activity = PostActivity.find_or_create_by(name: 'Playing')
PostActivity.find_or_create_by(name: "soccer", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "basketball", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "cricket", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "Baseball", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "Xbox", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "Video Games", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "Chess", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "playing cards", parent_id: parent_activity.id)
PostActivity.find_or_create_by(name: "board games", parent_id: parent_activity.id)
parent_activity = PostActivity.find_or_create_by(name: 'Supporting')

# # # # # # # # # # # # # # # # # # # # # # # # # # #
#               PermissionType List                 #
# # # # # # # # # # # # # # # # # # # # # # # # # # #
permission_type1 = PermissionType.find_or_create_by(action_name: "Public", action_description: "Anyone on or off EdYou", action: "public")
permission_type2 = PermissionType.find_or_create_by(action_name: "Friends", action_description: "Your friends on EdYou", action: "friends")
permission_type3 = PermissionType.find_or_create_by(action_name: "Friends, except...", action_description: "Don't show to some friends", action: "except_friends")
permission_type4 = PermissionType.find_or_create_by(action_name: "Specific friends...", action_description: "Only show to some friends", action: "specific_friends")
permission_type5 = PermissionType.find_or_create_by(action_name: "Only me", action_description: "Only me", action: "private")
permission_type6 = PermissionType.find_or_create_by(action_name: "Close friends", action_description: "Your custom list", action: "close_friends")

# # # # # # # # # # # # # # # # # # # # # # # # # # #
#               Permission List                     #
# # # # # # # # # # # # # # # # # # # # # # # # # # #
Permission.find_or_create_by(permission_type_id: permission_type1.id,action_object: 'Post')
Permission.find_or_create_by(permission_type_id: permission_type2.id,action_object: 'Post')
Permission.find_or_create_by(permission_type_id: permission_type3.id,action_object: 'Post')
Permission.find_or_create_by(permission_type_id: permission_type4.id,action_object: 'Post')
Permission.find_or_create_by(permission_type_id: permission_type5.id,action_object: 'Post')
Permission.find_or_create_by(permission_type_id: permission_type6.id,action_object: 'Post')

Permission.find_or_create_by(permission_type_id: permission_type1.id,action_object: 'Album')
Permission.find_or_create_by(permission_type_id: permission_type2.id,action_object: 'Album')
Permission.find_or_create_by(permission_type_id: permission_type3.id,action_object: 'Album')
Permission.find_or_create_by(permission_type_id: permission_type4.id,action_object: 'Album')
Permission.find_or_create_by(permission_type_id: permission_type5.id,action_object: 'Album')
Permission.find_or_create_by(permission_type_id: permission_type6.id,action_object: 'Album')
